version: "3.9"

services:

  postgres_db:
    image: postgres:16
    container_name: postgres_db
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_cms

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
      - backend_net

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'

    ports:
      - "5050:80"

    depends_on:
      postgres_db:
        condition: service_healthy

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    networks:
      - backend_net


  fastapi_backend:
    build: ./backend
    container_name: fastapi_backend
    restart: always

    depends_on:
      postgres_db:
        condition: service_healthy

    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres_db:5432/blog_cms
      RUN_SEED: "false"

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    networks:
      - backend_net


  frontend:
    build: ./frontend
    container_name: next_frontend
    restart: always

    depends_on:
      - fastapi_backend

    ports:
      - "3000:3000"

    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

    command: npm run dev

    networks:
      - backend_net


volumes:
  pgdata:
  pgadmin_data:

networks:
  backend_net:
    driver: bridge